{% set name = "pymediainfo" %}
{% set version = "7.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d5df59ecc615e24c56f303b8f651579c6accab7265715e5d429186d7ba21514
  patches:
    - no-accented-filename-under-win.patch  # [win]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python
    - libmediainfo

test:
  source_files:
    - tests
  imports:
    - pymediainfo
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around the MediaInfo library

  doc_url: https://pymediainfo.readthedocs.io/
  dev_url: https://github.com/sbraz/pymediainfo

extra:
  recipe-maintainers:
    - anjos
    - sodre
