{% set name = "pymediainfo" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d996c69d50081a24d6dca9679abf43ffd2be368b065f953c2c9082e5d649c734

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - setuptools
    - libmediainfo

test:
  source_files:
    - tests
  imports:
    - pymediainfo
  requires:
    - pip
    - pytest
    - pytest-runner
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around the MediaInfo library

  doc_url: https://pymediainfo.readthedocs.io/
  dev_url: https://github.com/sbraz/pymediainfo

extra:
  recipe-maintainers:
    - anjos
    - sodre
