{% set name = "pymediainfo" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b78e979e42e50a714f439452679c53d9e99b6f35a25542837aee97886d06dd45
  patches:
    - fix-python-38-dll-load.patch  # [win and py==38]
    - no-accented-filename-under-win.patch  # [win]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools
    - libmediainfo

test:
  source_files:
    - tests
  imports:
    - pymediainfo
  requires:
    - pip
    - pytest
    - pytest-runner
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/sbraz/pymediainfo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper around the MediaInfo library

  doc_url: https://pymediainfo.readthedocs.io/
  dev_url: https://github.com/sbraz/pymediainfo

extra:
  recipe-maintainers:
    - anjos
    - sodre
